// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sancta-familia/SacredModern.tsx": () => import("../components/mockups/sancta-familia/SacredModern.tsx"),
  "./components/mockups/sancta-familia/WarmEditorial.tsx": () => import("../components/mockups/sancta-familia/WarmEditorial.tsx"),
  "./components/mockups/sancta-familia/WeeklySchoolProgress.tsx": () => import("../components/mockups/sancta-familia/WeeklySchoolProgress.tsx")
};
